### ISSUE TITLE
Unhandled promise rejection

### ISSUE THREAD

**Issue by Steff42** [Patrick-Walther/ioBroker.pvforecast#5]
Hallo,
ich habe gestern das Update auf die Version 0.0.3 gemacht. Hat soweit gut ausgesehen. Heute morgen um 4 Uhr wollte der Adapter dann neue Daten holen, was auch geklappt hat - zumindest sehe ich im Objekt pvforecast.0.object korrekte Daten. Scheinbar ist der Adapter dann beim parsen der Daten mit o.g. Fehlermeldung abgeschmiert.
Hier mal der komplette Log-Auszug:

<html>
<body>

2021-08-31 04:01:00.027 - error: pvforecast.0 (18721) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2021-08-31 04:01:00.035 - error: pvforecast.0 (18721) unhandled promise rejection: dapter is not defined
2021-08-31 04:01:00.036 - error: pvforecast.0 (18721) ReferenceError: dapter is not defined
at Job.job (/opt/iobroker/node_modules/iobroker.pvforecast/main.js:210:2)
at Job.invoke (/opt/iobroker/node_modules/node-schedule/lib/Job.js:168:15)
at /opt/iobroker/node_modules/node-schedule/lib/Invocation.js:268:28
at Timeout._onTimeout (/opt/iobroker/node_modules/node-schedule/lib/Invocation.js:228:7)
at listOnTimeout (internal/timers.js:549:17)
at processTimers (internal/timers.js:492:7)
2021-08-31 04:01:00.036 - error: pvforecast.0 (18721) dapter is not defined
2021-08-31 04:01:00.038 - info: pvforecast.0 (18721) terminating
2021-08-31 04:01:00.038 - warn: pvforecast.0 (18721) Terminated (UNCAUGHT_EXCEPTION): Without reason
2021-08-31 04:01:00.649 - error: host.Smarthome instance system.adapter.pvforecast.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2021-08-31 04:01:00.649 - info: host.Smarthome Restart adapter system.adapter.pvforecast.0 because enabled
2021-08-31 04:01:30.679 - info: host.Smarthome instance system.adapter.pvforecast.0 started with pid 1980
2021-08-31 04:01:31.511 - info: pvforecast.0 (1980) starting. Version 0.0.3 in /opt/iobroker/node_modules/iobroker.pvforecast, node: v12.16.3, js-controller: 3.3.15
2021-08-31 04:01:31.536 - info: pvforecast.0 (1980) ThisUrl https://api.forecast.solar/estimate/xx.xxxxxx/x.xxxxxxx/xx/x/x.xx

</body>
</html>

Persönliche Daten in der URL sind absichtlich mit x überschrieben.

Siehst Du wo es da klemmt?

Gruß Steffen

**Comment by Steff42** [comment]
Ich glaube ich habe den Fehler gefunden im Code der Datei main.js ist in Zeile 210 ein Typo.

dort steht "dapter.log.debug('1 4 * * *');"
müsste das nicht "adapter.log.debug('1 4 * * *');" heißen? Da fehlt glaube ich ein "a"

Gruß Steffen

**Comment by Patrick-Walther** [comment]
habe den Fehler behoben.
Gruß
Patrick

**Comment by Patrick-Walther** [comment]
Hi,

danke für die Geduld sollte jetzt funktionieren!

**Comment by Steff42** [comment]
Kein Problem, bin ja froh das du das Script in einen Adapter "gegossen" hast.
Habe gerade eben aktualisiert, sieht nun gut aus.

Danke!
